name: CI

permissions:
  contents: read

on:
  push:
    branches: [mainline]
  pull_request:
    branches: [mainline]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9  # v9.0.0
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          uv sync --frozen --all-packages

      - name: Audit dependencies
        run: |
          uv audit
          uv run pip-audit --require-hashes -r requirements.txt

      - name: Run type checks
        run: |
          uv run ty check

      - name: Run linting checks
        run: |
          uv run ruff check

      - name: Run tests with Pytest
        run: |
          uv run pytest
